What I learn from 

<b>Introduction to Machine Learning with Python A GUIDE FOR DATA SCIENTISTS</b>

by <b>Andreas C. Müller & Sarah Guido</b>

During the 70 Days pre bootcamp online class with <b>Data Science Nigeria</b> #DSN

## Machine learning 
Is about extracting knowledge from data. It is a research field at the intersection of statistics, artificial intelligence, and computer science and is also known as predictive analytics or statistical learning.

Machine learning algorithms that learn from input/output pairs are called <b> supervised
learning </b> algorithms because a “teacher” provides supervision to the algorithms in the
form of the desired outputs for each example that they learn from.

Examples of supervised machine learning that a computer can solve includes:
1. Identifying the zip code from handwritten digits on an envelope
2. Determining whether a tumor is benign based on a medical image
3. Detecting fraudulent activity in credit card transactions

Machine learning algorithms that learn from only the input data, and no known output
data is given to the algorithm are called <b>unsupervised learning</b>,

Examples of unsupervised learning include:
1. Identifying topics in a set of blog posts
2. Segmenting customers into groups with similar preferences
3. Detecting abnormal access patterns to a website

When building a machine learning solution, you should keep in mind, the following questions:
What question(s) am I trying to answer? Do I think the data collected can answer
that question?
1. What is the best way to phrase my question(s) as a machine learning problem?
2. Have I collected enough data to represent the problem I want to solve? <b>(Good / Correct Data)</b>
3. What features of the data did I extract, and will these enable the right predictions?
4. How will I measure success in my application?
5. How will the machine learning solution interact with other parts of my research or business product?

One of the main advantages of using Python is the ability to interact directly with the code, using a terminal or other tools like the Jupyter Notebook

Libriries Like

1. Scikit Learn
2. Numpy
3. Pandas
4. Matplotlib
5. Scipy and more makes Machine Learning Possible and Fun

## My First Example In this book

### Classifying Iris Species (This is a Classification Problem In Supervised Learning; There are two type of problem in supervised learning, classification is one of them, the other is Regression)

My goal is to build a machine learning model that can learn from the measurements of these irises whose species is known, so that we can predict the species for a new iris.

`[iris flower.png]

In [1]:
#Loading Dataset from sklearn
#Sometimes you will be given dataset in form of csv, sometimes you will have to query from SQL database, 
#Sometimes to will have to find it yourself example like performing webscraping from a webpage/website
#Any which way Python got you covered (#libraries)
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [3]:
# Getting Some info about our Data Set
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()))
print(iris_dataset['DESCR'][:193] + "\n...")

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [4]:
#This print the target_names, that is the species of flower that we want to predict (Our Output)
print("Target names: {}".format(iris_dataset['target_names']))


Target names: ['setosa' 'versicolor' 'virginica']


In [5]:
#This print out the feature_names, the list of strings, giving the description of each feature (Input)
print("Feature names: \n{}".format(iris_dataset['feature_names']))

Feature names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
# Data Type
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [7]:
#Numbers of entries (rows) by the header (Column)
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


In [8]:
# Examples
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
#Computers Dont Understand String(Letter, Symbols) So The Need for us to encode our target
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


<b>Measuring Success</b> Why do I Training and Testing Data
To know whether we should trust its predictions.

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
iris_dataset['data'], iris_dataset['target'], random_state=0)

We Divided our data into two because we need to train our data (Like a Teacher in a Class) then we test our data (Like a Teacher Knowing whether His/Her Students really understand the subject. Do you get the gist ;-).)

In [11]:
# No of our traning data (In the teacher/student story, this will be the no of example our teachers 
# gives us in class) 
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))

X_train shape: (112, 4)
y_train shape: (112,)


Now unlike us (Humans) we have to give our computers lots and lots of 
example,the more example we give the our computers, the more our computer perform well 

In [12]:
# No of our test data (In the teacher/student story, this will be the accessment 
#(CAs: Classwork Home-work Exam Project) our teachers 
# gives us in school) 
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_test shape: (38, 4)
y_test shape: (38,)
